inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
  TargetRubyVersion: 2.6.1

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
